Revert "Fixed error Variant.h:43:33: error: redeclaration of ‘typedef long int libVariant::Variant::sint32’"
This reverts commit b4ddcc413358b25f3d28f78f0abe81f9d7a917d8.